### ISSUE TITLE
Does not work? Need setup instructions 

### ISSUE THREAD

**Issue by Nathoufresh** [tecosaur/engrave-faces#1]
This looks nice, how do you set it up? In my config:

```
(use-package engrave-faces
    :load-path "~/.emacs.d/engrave-faces"
    :config
    (setq org-latex-listings 'engraved))
```

But src blocks aren't  highlighted on latex export.

**Comment by tecosaur** [comment]
Currently, there's a lot more that goes into using this with Org, since it's my hope that this can become a generic backend.

See: https://tecosaur.github.io/emacs-config/config.html#pretty-code-blocks

**Comment by tecosaur** [comment]
Update: this has now been merged into Org. It will be described in the next next TMiO post.
