### ISSUE TITLE
Not working with doom-nord theme

### ISSUE THREAD

**Issue by shaunsingh** [tecosaur/engrave-faces#2]
Hi, I'm using this package to color the syntax for my exports. However, it seems like using the doom-nord theme results in weird colors: 
![image](https://user-images.githubusercontent.com/71196912/135735408-ede76363-3078-4ecd-abc8-b077c7453bf8.png)
Other themes, like doom-vibrant or doom-one-light work just fine
![image](https://user-images.githubusercontent.com/71196912/135735439-0a95d258-ea61-4472-8b87-0f5e98b0cb9f.png)
Any idea what could be happening?

**Comment by tecosaur** [comment]
Try `(setq engrave-faces-preset-styles (engrave-faces-generate-preset))`.

**Comment by tecosaur** [comment]
Huh, I do notice `doom-nord` in particular not working with `ox-chameleon`. That's weird.

**Comment by shaunsingh** [comment]
> (setq engrave-faces-preset-styles (engrave-faces-generate-preset))

That fixes it, what does it do?

**Comment by tecosaur** [comment]
Have you read the docstrings?
