### ISSUE TITLE
Not self-documenting

### ISSUE THREAD

**Issue by PhilHudson** [tecosaur/engrave-faces#5]
What do you do with it once you've installed it?

**Comment by PhilHudson** [comment]
Seriously? I've given you important and useful feedback here, and you've come back with... that? Your. Doco. Does. Not. Describe. How. To. Use. It. Not. Even. A. Little. Bit. What do you do? `require` it? Then what? You must have seen an Emacs package before. They describe how to use themselves in fairly standard ways. Do that. Don't make users read every line of code to deduce what you mean by "use it".

**Comment by elken** [comment]
I don't want to pile onto this, but quoting the README

> This is very much a work in progress

It's fair that a package that isn't in a state of completion doesn't have fleshed out documentation yet. The key functions have docstrings, and if you're unsatisfied with the degree of that you are welcome to try and improve it :D

**Comment by tecosaur** [comment]
Actually, it will only take me a moment to add a demo of the predominant entry point here.

```lisp
(defun engrave-faces-demo--face-apply (faces content)
  (format "{%S %s}" faces content))

(engrave-faces-define-backend
 "demo" ".demo" #'engrave-faces-demo--face-apply)

;; Using our new "demo" backend

(with-current-buffer
    (with-temp-buffer
      (emacs-lisp-mode)
      (insert "(message \"hey %s\" 'you)")
      (font-lock-ensure)
      (engrave-faces-demo-buffer))
  (buffer-string))
```

For more comprehensive examples, there's `engave-faces-{html,latex,ansi}.el`.
