### ISSUE TITLE
Colour specification for textbox assumes colour in form #AABBCC

### ISSUE THREAD

**Issue by ericsfraga** [tecosaur/engrave-faces#7]
If you have specified the foreground colour for a face using a name, e.g. "DarkSlateBlue", the LaTeX code produced uses "arkSlateBlue" as the colour which of course does not exist. The code assumes that there is a # at the start of the colour specification.
I am happy to use hex strings for colours but a heads up in the documentation would be welcome!
Otherwise, this package is excellent and makes code listings look very nice in both LaTeX and HTML documents when exporting from org mode. Thank you.

**Comment by tecosaur** [comment]
Thanks for mentioning this Eric, I'll note the restriction in the docstring of `engrave-faces-current-preset-style`.

Tangentially, you might be interested to see that when generating presets named colours are converted to hex here:
https://github.com/tecosaur/engrave-faces/blob/94fbdb021f0504982d6902b8df2b0a5c79a1d9da/engrave-faces.el#L406-L411

**Comment by tecosaur** [comment]
Noted in 0dbe2e088f58ad3b50223cad9b5ab0477fc1ccb9.

**Comment by tecosaur** [comment]
> Otherwise, this package is excellent and makes code listings look very nice in both LaTeX and HTML documents when exporting from org mode. Thank you.

That's great to hear! What did you do for HTML though? I've only set up integrations for `ox-latex` so far. At some point in the future it would be nice to extend this to `ox-html`, `ox-ascii`, and `ox-odt`, but I"m content with LaTeX support for now.

**Comment by ericsfraga** [comment]
For HTML, I used CSS to style the code. Org exports with code elements wrapped with class specifications such as org-function-name etc.
