### ISSUE TITLE
Compiler warnings

### ISSUE THREAD

**Issue by yantar92** [tecosaur/engrave-faces#8]
In engrave-faces-define-backend:
engrave-faces.el:79:11: Warning: docstring wider than 80 characters

In engrave-faces-buffer:
engrave-faces.el:134:48: Warning: Unused lexical variable `engrave-faces-current-preset-style'
engrave-faces.el:139:12: Warning: reference to free variable ‘engrave-faces-current-preset-style’

In engrave-faces-attribute-values:
engrave-faces.el:225:55: Warning: reference to free variable ‘engrave-faces-current-preset-style’
engrave-faces.el:338:1: Warning: Variable ‘engrave-faces-current-preset-style’ declared after its first use

**Comment by tecosaur** [comment]
Thanks Ihor, I'll have a shot at fixing all these later today.

**Comment by tecosaur** [comment]
I think these should be fixed in fe356507efb8c9b051c2a67213ba292f932a88bc.
