### ISSUE TITLE
`org-latex-engraved-theme` does not impact syntax highlighting

### ISSUE THREAD

**Issue by hydrobeam** [tecosaur/engrave-faces#9]
## Description of issue
Setting `org-latex-engraved-theme` to `t` seems to only impact the background colour of exported code blocks in pdf, and the syntax highlighting remains the default colour. However, specifying:
```
#+attr_latex: :engraved-theme THEME
``` 
above a specific code block causes it to be correctly highlighted.

setting `#+latex_engraved_theme: THEME` in the file does not cause syntax highlighting to occur.

## Screenshots

- Appearance of source code in buffer 
![image](https://user-images.githubusercontent.com/70682032/188197584-aa24410b-fed2-4e3f-8b23-9b26a2670d55.png)

- The way it's rendered normally
<img width="550" alt="image" src="https://user-images.githubusercontent.com/70682032/188197664-543f6dbc-034c-4348-a9bf-bac987d696ba.png">

- Appearance of export with specifying the properties
<img width="534" alt="image" src="https://user-images.githubusercontent.com/70682032/188197714-379a7ce2-75b5-4ec6-9ff7-80ac69b498c5.png">

## Config
I'm using Doom Emacs, here's my relevant config

- `engrave-faces`:
```lisp
(use-package! engrave-faces-latex
  :after ox-latex
  :config
  (add-to-list 'org-latex-engraved-options '("linenos" "true"))
  (setq org-latex-engraved-theme "t")
  )
```
- general `org` config
```
  (setq org-latex-src-block-backend 'engraved)
```

**Comment by tecosaur** [comment]
Have you tried setting `org-latex-engraved-theme` to `t` not `"t"` ?

**Comment by hydrobeam** [comment]
> Have you tried setting org-latex-engraved-theme to t not "t" ?

If i do that, then the I get an error in the modeline when compiling to pdf: `Wrong type argument: stringp, t`

**Comment by tecosaur** [comment]
This may be fixed by https://git.tecosaur.net/tec/org-mode/commit/3c18d1dfb3f7914f253e26ee3be7813d46659307

**Comment by tecosaur** [comment]
Let me know if this is not fixed.
